services:
  # Service to generate keyfile and password file if they don't exist
  setup-generator:
    image: alpine:latest
    container_name: setup-generator
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - MONGOT_PASSWORD=${MONGOT_PASSWORD:-mongotPassword}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    command: >
      sh -c "
        echo 'Setting up security files...';
        echo 'Admin password: [HIDDEN]';
        echo 'Mongot password: [HIDDEN]';
        
        # Generate keyfile if it doesn't exist
        if [ ! -f keyfile ]; then
          echo 'Generating keyfile...';
          apk add --no-cache openssl;
          openssl rand -base64 756 > keyfile;
          chmod 400 keyfile;
          echo 'Keyfile generated successfully';
        else
          echo 'Keyfile already exists, skipping generation';
        fi;
        
        # Create password file with specified password
        echo 'Creating password file...';
        echo -n "$MONGOT_PASSWORD" > passwordFile;
        chmod 600 passwordFile;
        echo 'Password file created successfully';
        
        echo 'Setup completed successfully';
      "
    profiles:
      - setup

  mongod:
    image: mongodb/mongodb-community-server:latest
    container_name: mongod-community
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD:-admin}
      MONGOT_PASSWORD: ${MONGOT_PASSWORD:-mongotPassword}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    command: >-
      mongod
      --config /etc/mongod.conf
      --replSetMember=mongod.search-community:27017
    ports:
      - "27017:27017"
    volumes:
      - mongod_data:/data/db
      - mongod_configdb:/data/configdb
      - ./mongod.conf:/etc/mongod.conf:ro
      - ./keyfile:/keyfile:ro
      - ./sampledata.archive:/sampledata.archive:ro
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - search-community
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongot:
    image: mongodb/mongodb-community-search:latest
    container_name: mongot-community
    ports:
      - "27028:27028"  # gRPC server port
      - "8080:8080"    # Health check port  
      - "9946:9946"    # Metrics port
    volumes:
      - mongot_data:/data/mongot
      - ./mongot.conf:/mongot-community/config.default.yml:ro
      - ./passwordFile:/passwordFile:ro
    networks:
      - search-community
    depends_on:
      mongod:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://mongot-community.search-community:9946/metrics"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # MongoDB exporter for MongoDB Community Server metrics
  mongodb-exporter:
    image: percona/mongodb_exporter:0.39
    container_name: mongodb-exporter
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://admin:${ADMIN_PASSWORD:-admin}@mongod:27017
    command: 
      - --mongodb.uri=mongodb://admin:${ADMIN_PASSWORD:-admin}@mongod:27017
      - --web.listen-address=0.0.0.0:9216
      - --log.level=info
      - --collector.diagnosticdata
      - --collector.replicasetstatus
      - --collector.dbstats
      - --collector.topmetrics
      - --collector.indexstats
      - --collector.collstats
    networks:
      - search-community
    depends_on:
      mongod:
        condition: service_healthy
    restart: unless-stopped

  # Prometheus server
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - search-community
    depends_on:
      mongod:
        condition: service_healthy
      mongot:
        condition: service_healthy
    restart: unless-stopped

  # Grafana for visualization (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - search-community
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  mongod_data:
  mongod_configdb:
  mongot_data:

networks:
  search-community:
    name: search-community
    driver: bridge
    external: true  # Use an external network if it exists. Comment this line if you want to create a new network.