apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mongodb

resources:
  - kubernetes/00-namespace.yml
  - kubernetes/01-secrets.yml
  - kubernetes/02-mongodb-community.yml
  - kubernetes/03-mongot-deployment.yml
  - kubernetes/04-monitoring.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-datasources
    files:
      - grafana/provisioning/datasources/prometheus.yml
  - name: grafana-dashboards
    files:
      - grafana/provisioning/dashboards/dashboards.yml
      - grafana/provisioning/dashboards/mongodb-dashboard.json

labels:
  - includeSelectors: false
    pairs:
      app: mongodb-community-search
      managed-by: kustomize
