apiVersion: v1
kind: Secret
metadata:
  name: mdb-admin-user-password
  namespace: mongodb
type: Opaque
stringData:
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: mdb-user-password
  namespace: mongodb
type: Opaque
stringData:
  password: userpassword

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-search-sync-source-password
  namespace: mongodb
type: Opaque
stringData:
  password: searchpassword

