apiVersion: mongodb.com/v1
kind: MongoDBSearch
metadata:
  name: mongodb
  namespace: mongodb
spec:
  prometheus:
    port: 9946

  resourceRequirements:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "500m"
      memory: 1Gi
