apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-generate-metrics
  namespace: mongodb
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: generate-metrics
          image: mongodb/mongodb-community-server:8.2.0-ubi8
          imagePullPolicy: IfNotPresent
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mdb-admin-user-password
                  key: password
          volumeMounts:
            - name: generate-metrics-script
              mountPath: /scripts/generate-metrics-k8s.sh
              subPath: generate-metrics-k8s.sh
          command:
            - /bin/bash
            - -lc
            - /bin/bash /scripts/generate-metrics-k8s.sh
      volumes:
        - name: generate-metrics-script
          configMap:
            name: generate-metrics-script
