apiVersion: v1
kind: Secret
metadata:
  name: my-mongodb-keyfile
type: Opaque
data:
  keyfile: "SlTIv9cb4a+gNdjwSFqY5mqEy/r9mzxXuU56++/hxy76I1OYjvnh60hANgf7e6AB
Q3DbAUGt4zSXhVmDtei6qJrxlwGU4UclvoNR5WPJjmnH43wU9jyZVM8FXUCAY6MS
G5uadrBIJzAFg7CJOmmRKqqQIPzE450OlPxS5HhM4uC/MSIm7nGwFpVfgq3I04Xz
B14tXpHQxWh1DLLR1UAhw+NPLtwNa5v+EBdZYpAyUDHh23IvQ4eDs110/ZRSaefo
cxtkMV/W8lVaXY3iU58rPWad1x/QT4eHniqNzV8/uyvH00z7UWEGW4BkguFMWu5a
cK8aVtmw2qNOebIFVNRbUtT5Ga48r2AKlrW+9Xx13iKIBuQfvU7cWoLFYlUbSBj6
RNUh00aaZEXAaxIbXBYvI7LwN4K5fe+R5Sv7jTl54H0xA1N8X3WNRtCYgtuZFgLA
SzbE2dfVNlyvE3RXnjmrWweDYwKBsy9YSRyEK4xxInF02MvEo60k0HYDwUCyE7Os
141A3fr5yNsISmIcKKqgUh5Kdss5IUgo/K0ycVZdmHb4fGbwh+j7nZaZKoBI9JK5
bzQdMa9PBqLs3OW1HeawedHHUHtNF0vvnPONbzrgloKRxxJqBgFIIEh2esKhI3Pi
bkv69jomQrzQbc6QZV7Xjhl6ZZ4AMipGNPLVE8y9965GuMfLMMp7mp6N9M5nx5Ic
2Ctbdpz4/2Uf7mDTbNSeLUkxXBNtRJpPhba77XcfinEF4tgNz8QGFdD0bcpJ5IIH
2AToKzwrZnX/HdqZ4VxKipZMAcbQkmcIOLA0y7JR4c7h5yYNSGe2eWRl1USFGwld
xChkFIOe6+WL5oyn7vMUFhmAS0fXclukowtPJegFQzMqvIoqzsTPSzIOE0dafnqE
p3DWf/XPVLhnmzX62NIGKF8Rslpw55qXB8P89/IBTh9awe2pw7mpRj/tYRTH3rO3
UZNT3TCNuyj/a1KNaO1NWoNhaHU2/7uh5MYvmukILJx4SlEo"